
List  shawarmaMeat = [
  (
    productTitle: "شـــاورما شـــامي لـــحم",
    productSubTitle: " Shami Meat Shawarma ",
    productImg: "img/new/شـــاورما شـــامي لـــحم.png",
    productPrice: "12",
    productKaloris: "773",
  ),
  (
    productTitle: "شـــاورما صـــامولي لـــحم",
    productSubTitle: " Samoli Meat Shawarma",
    productImg: "img/new/شـــاورما صـــامولي لـــحم.png",
    productPrice: "17",
    productKaloris: "850",
  ),
  (
    productTitle: "شـــاورما صـــاج لـــحم ",
    productSubTitle: " Saj Meat Shawarma",
    productImg: "img/new/شـــاورما صـــاج لـــحم.png",
    productPrice: "15",
    productKaloris: "844",
  ),
  (
    productTitle: "شـــاورما عـــربي لـــحم",
    productSubTitle: "Arabic Meat Shawarma",
    productImg: "img/new/شـــاورما عـــربي لـــحم.png",
    productPrice: "22",
    productKaloris: "500",
  ),
  (
    productTitle: "شـــاورما عـــربي لـــحم دبـــل",
    productSubTitle: "Arabic Meat Shawarma Double",
    productImg: "img/new/شـــاورما عـــربي لـــحم دبـــل.png",
    productPrice: "32",
    productKaloris: "796",
  ),
  (
    productTitle: "وجـــبة أصـــابع لـــحم",
    productSubTitle: "Meat Fingers Meal",
    productImg: "img/new/وجـــبة أصـــابع لـــحم.png",
    productPrice: "27",
    productKaloris: "740",
  ),
  (
    productTitle: "طـــبق شـــاورما لـــحم مع الأرز",
    productSubTitle: " Shawarma Meal with Rice",
    productImg: "img/new/طـــبق شـــاورما لـــحم مع الأرز.png",
    productPrice: "35",
    productKaloris: "590",
  ),
  (
    productTitle: " صـــحن فـــرط شـــاورما لـــحم",
    productSubTitle: "Meat Shawarma (Plate)",
    productImg: "img/new/صـــحن فـــرط شـــاورما لـــحم.png",
    productPrice: "40",
    productKaloris: "896",
  ),
  (
    productTitle: "نـــصف كـــيلو شـــاورما لـــحم",
    productSubTitle: " Shawarma Meal with Rice",
    productImg: "img/new/نـــصف كـــيلو شـــاورما لـــحم.png",
    productPrice: "65",
    productKaloris: "1435",
  ),
  (
    productTitle: " كـــيلو شـــاورما لـــحم",
    productSubTitle: " Shawarma Meal with Rice",
    productImg: "img/new/كـــيلو شـــاورما لـــحم.png",
    productPrice: "120",
    productKaloris: "2870",
  ),
];
// ==================================== Chicken_Shawarma ==============================================================================
  List  shawarmaCheken = [
  (
    productTitle: "شـــاورما شـــامي دجـــاج",
    productSubTitle: "Shami Chicken Shawarma",
    productImg: "img/new/شـــاورما شـــامي دجـــاج.png",
    productPrice: "11",
    productKaloris: "403",
  ),
  (
    productTitle: "شـــاورما صـــامولي دجـــاج",
    productSubTitle: "Samoli Chicken Shawarma",
    productImg: "img/new/شـــاورما صـــامولي دجـــاج.png",
    productPrice: "16",
    productKaloris: "450",
  ),
  (
    productTitle: "شـــاورما صـــاج دجـــاج",
    productSubTitle: "Saj Chicken Shawarma",
    productImg: "img/new/شـــاورما صـــاج دجـــاج.png",
    productPrice: "14",
    productKaloris: "600",
  ),
  (
    productTitle: "شـــاورما عـــربي دجـــاج",
    productSubTitle: "Arabic Meat Shawarma",
    productImg: "img/new/شـــاورما عـــربي دجـــاج.png",
    productPrice: "20",
    productKaloris: "480",
  ),
  (
    productTitle: "شـــاورما عـــربي دجـــاج دبـــل",
    productSubTitle: "Arabic Chicken Shawarma Double",
    productImg: "img/new/شـــاورما عـــربي دجـــاج دبـــل.png",
    productPrice: "30",
    productKaloris: "550",
  ),
  (
    productTitle: "وجـــبة أصـــابع دجـــاج",
    productSubTitle: "Chicken Fingers Meal",
    productImg: "img/new/وجـــبة أصـــابع دجـــاج.png",
    productPrice: "25",
    productKaloris: "592",
  ),
  (
    productTitle: "وجـــبة شـــاورما دجـــاج مع الأرز",
    productSubTitle: "Chicken Shawarma Meal with Rice",
    productImg: "img/new/وجـــبة شـــاورما دجـــاج مع الأرز.png",
    productPrice: "30",
    productKaloris: "531",
  ),
  (
    productTitle: "صـــحن فـــرط شـــاورما دجـــاج",
    productSubTitle: "Chicken Shawarma (Plate)",
    productImg: "img/new/صـــحن فـــرط شـــاورما دجـــاج.png",
    productPrice: "30",
    productKaloris: "662",
  ),
  (
    productTitle: "نـــصف كـــيلو شـــاورما دجـــاج",
    productSubTitle: "Chicken Shawarma (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو شـــاورما دجـــاج.png",
    productPrice: "55",
    productKaloris: "1390",
  ),
  (
    productTitle: " كـــيلو شـــاورما دجـــاج",
    productSubTitle: " Shawarma Meal with Rice",
    productImg: "img/new/كـــيلو شـــاورما دجـــاج.png",
    productPrice: "100",
    productKaloris: "2780",
  ),
  (
    productTitle: "خـــلطة شـــاورما إنـــجوي",
    productSubTitle: "Enjoy Mix Shawarma",
    productImg: "img/new/خـــلطة شـــاورما إنـــجوي.png",
    productPrice: "18",
    productKaloris: "1100",
  ),
];

// ================================== Grills_Section ========================================
List GrillsSection = [
  (
    productTitle: "مـــشويّات مـــشكّلة (وجـــبة)",
    productSubTitle: "Mixed Grills (Meal)",
    productImg: "img/new/مـــشويّات مـــشكّلة (وجـــبة).png",
    productPrice: "40",
    productKaloris: "1187",
  ),
  (
    productTitle: "طـــبق كـــباب لـــحم",
    productSubTitle: "Kebab Meat Dish",
    productImg: "img/new/طـــبق كـــباب لـــحم.png",
    productPrice: "35",
    productKaloris: "1065",
  ),
  (
    productTitle: "طـــبق كـــباب دجـــاج",
    productSubTitle: "Kebab Chicken Dish",
    productImg: "img/new/طـــبق كـــباب دجـــاج.png",
    productPrice: "30",
    productKaloris: "1055",
  ),
  (
    productTitle: "طـــبق شـــيش طـــاووق",
    productSubTitle: "Shish Tawook Dish",
    productImg: "img/new/طـــبق شـــيش طـــاووق.png",
    productPrice: "30",
    productKaloris: "600",
  ),
  (
    productTitle: "طـــبق ريـــش",
    productSubTitle: "Feathers Dish",
    productImg: "img/new/طـــبق ريـــش.png",
    productPrice: "45",
    productKaloris: "617",
  ),
  (
    productTitle: "طـــبق أوصـــال",
    productSubTitle: "Awsil Meat Dish",
    productImg: "img/new/طـــبق أوصـــال.png",
    productPrice: "40",
    productKaloris: "751",
  ),
  (
    productTitle: "طـــبق عـــرايس لـــحم مـــارينا",
    productSubTitle: "Arayes Meat Marina Dish",
    productImg: "img/new/طـــبق عـــرايس لـــحم مـــارينا.png",
    productPrice: "30",
    productKaloris: "488",
  ),
  (
    productTitle: "وجـــبة كـــباب مع الأرز ",
    productSubTitle: "Meal of Kebab with Rice",
    productImg: "img/new/وجـــبة كـــباب مع الأرز.png",
    productPrice: "35",
    productKaloris: "608",
  ),
  (
    productTitle: "وجـــبة شيش مع الأرز",
    productSubTitle: "Meal of Shish with Rice",
    productImg: "img/new/وجـــبة شيش مع الأرز.png",
    productPrice: "30",
    productKaloris: "466",
  ),
  (
    productTitle: " نـــصف كـــيلو مـــشويّات مـــشكّلة",
    productSubTitle: " Shawarma Meal with Rice",
    productImg: "img/new/نـــصف كـــيلو مـــشويّات مـــشكّلة.png",
    productPrice: "75",
    productKaloris: "2175",
  ),
  (
    productTitle: "كـــيلو مـــشويّات مـــشكّلة",
    productSubTitle: "  Mixed Grills (Kilo)",
    productImg: "img/new/كـــيلو مـــشويّات مـــشكّلة.png",
    productPrice: "140",
    productKaloris: "4350",
  ),
  (
    productTitle: "نـــصف كـــيلو أوصـــال",
    productSubTitle: " Joints (Half Kilo)",
    productImg: "img/new/خـــلطة شـــاورما إنـــجوي.png",
    productPrice: "80",
    productKaloris: "2310",
  ),
  (
    productTitle: "كـــيلو أوصـــال",
    productSubTitle: "Joints (Kilo)",
    productImg: "img/new/كـــيلو أوصـــال.png",
    productPrice: "150",
    productKaloris: "4600",
  ),
  (
    productTitle: "نـــصف كـــيلو كـــباب لـــحم",
    productSubTitle: "Kebab Meat (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو كـــباب لـــحم.png",
    productPrice: "75",
    productKaloris: "2130",
  ),
  (
    productTitle: "كـــيلو كـــباب لـــحم",
    productSubTitle: "Kebab Meat (Kilo)",
    productImg: "img/new/كـــيلو كـــباب لـــحم.png",
    productPrice: "140",
    productKaloris: "4260",
  ),
  (
    productTitle: "نـــصف كـــيلو شـــيش طـــاووق",
    productSubTitle: "Shish Tawook (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو شـــيش طـــاووق.png",
    productPrice: "70",
    productKaloris: "493",
  ),
  (
    productTitle: "كـــيلو شـــيش طـــاووق",
    productSubTitle: "Shish Tawook (Kilo)",
    productImg: "img/new/كـــيلو شـــيش طـــاووق.png",
    productPrice: "130",
    productKaloris: "1000",
  ),
  (
    productTitle: "نـــصف كـــيلو كـــباب دجـــاج",
    productSubTitle: "Kebab Chicken (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو كـــباب دجـــاج.png",
    productPrice: "70",
    productKaloris: "2210",
  ),
  (
    productTitle: "كـــيلو كـــباب دجـــاج",
    productSubTitle: "Kebab Chicken (Kilo)",
    productImg: "img/new/كـــيلو كـــباب دجـــاج.png",
    productPrice: "130",
    productKaloris: "4220",
  ),
  (
    productTitle: "نـــصف كـــيلو ريـــش",
    productSubTitle: "Feathers (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو ريـــش.png",
    productPrice: "80",
    productKaloris: "1770",
  ),
  (
    productTitle: "ســـاندويتش دجـــاج شـــيش",
    productSubTitle: "Sandwich Chicken Shish",
    productImg: "img/new/ســـاندويتش دجـــاج شـــيش.png",
    productPrice: "15",
    productKaloris: "380",
  ),
  (
    productTitle: "ســـاندويتش كـــباب دجـــاج",
    productSubTitle: "Sandwich Chicken Kebab",
    productImg: "img/new/ســـاندويتش كـــباب دجـــاج.png",
    productPrice: "15",
    productKaloris: "215",
  ),
  (
    productTitle: "كـــباب لـــحم",
    productSubTitle: " Meat Kebab",
    productImg: "img/new/كـــباب لـــحم.png",
    productPrice: "16",
    productKaloris: "223",
  ),
  (
    productTitle: "أوصـــال",
    productSubTitle: "Awsal",
    productImg: "img/new/أوصـــال.png",
    productPrice: "16",
    productKaloris: "323",
  ),
  (
    productTitle: "وجـــبة لـــحم بالـــصينيّة مع الخـــضار",
    productSubTitle: "Meat with Vegetables (Meal)",
    productImg: "img/new/وجـــبة لـــحم بالـــصينيّة مع الخـــضار.png",
    productPrice: "40",
    productKaloris: "843",
  ),
  (
    productTitle: "نص كيلو لـــحم بالـــصينيّة مع الخـــضار",
    productSubTitle: "Meat with Vegetables (Half Kilo)",
    productImg: "img/new/نص كيلو لـــحم بالـــصينيّة مع الخـــضار.png",
    productPrice: "65",
    productKaloris: "1425",
  ),
  (
    productTitle: "كيلو لـــحم بالـــصينيّة مع الخـــضار",
    productSubTitle: "Meat with Vegetables ( Kilo)",
    productImg: "img/new/وجـــبة لـــحم بالـــصينيّة مع الخـــضار.png",
    productPrice: "130",
    productKaloris: "2830",
  ),
  (
    productTitle: "لـــحم بالـــصينيّة",
    productSubTitle: "Plate of Meat (Meal) ",
    productImg: "img/new/لـــحم بالـــصينيّة.png",
    productPrice: "40",
    productKaloris: "843",
  ),
  (
    productTitle: "نـــصف كـــيلو لـــحمه بالـــصينيّة",
    productSubTitle: "Meat (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو لـــحمه بالـــصينيّة.png",
    productPrice: "65",
    productKaloris: "1400",
  ),
  (
    productTitle: "كيلو لـــحمه بالـــصينيّة",
    productSubTitle: "Plate of Meat (Kilo)",
    productImg: "img/new/نـــصف كـــيلو لـــحمه بالـــصينيّة.png",
    productPrice: "130",
    productKaloris: "2815",
  ),
  (
    productTitle: "كـــيلو لـــحمه مع طـــحينة",
    productSubTitle: "Meat (Half Kilo)",
    productImg: "img/new/كـــيلو لـــحمه مع طـــحينة.png",
    productPrice: "130",
    productKaloris: "2750",
  ),
  (
    productTitle: "نـــصف كـــيلو لـــحمه مع طـــحينة",
    productSubTitle: "Meat with Tahini (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو لـــحمه مع طـــحينة.png",
    productPrice: "65",
    productKaloris: "1370",
  ),
  (
    productTitle: "وجـــبة لـــحمه مع طـــحينة",
    productSubTitle: "Meat with Tahini (Meal)",
    productImg: "img/new/نـــصف كـــيلو لـــحمه بالـــصينيّة.png",
    productPrice: "40",
    productKaloris: "687",
  ),
  (
    productTitle: "كـــيلو كـــباب هـــندي",
    productSubTitle: "Indian Kebab (Kilo)",
    productImg: "img/new/كـــيلو كـــباب هـــندي.png",
    productPrice: "120",
    productKaloris: "2230",
  ),
  (
    productTitle: "نـــصف كـــيلو كـــباب هـــندي",
    productSubTitle: "Indian Kebab (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو كـــباب هـــندي.png",
    productPrice: "65",
    productKaloris: "1120",
  ),
  (
    productTitle: "كـــباب هـــندي - وجـــبة",
    productSubTitle: "Indian Kebab (Meal)",
    productImg: "img/new/كـــباب هـــندي - وجـــبة.png",
    productPrice: "40",
    productKaloris: "550",
  ),
];

// ======================= Hot Appetizers Section ================================================================
List HotAppetizersSection = [
  (
    productTitle: "حـــبّة كـــبّة مـــقليّة",
    productSubTitle: "Fried Kibbeh",
    productImg: "img/new/حـــبّة كـــبّة مـــقليّة.png",
    productPrice: "4",
    productKaloris: "160",
  ),
  (
    productTitle: "حـــبّة كـــبّة مـــشويّة",
    productSubTitle: "Grilled Kibbeh",
    productImg: "img/new/حـــبّة كـــبّة مـــشويّة.png",
    productPrice: "7",
    productKaloris: "152",
  ),
  (
    productTitle: "بـــطاطا مـــقليّة - حـــجم كـــبير",
    productSubTitle: "French Fries (Large)",
    productImg: "img/new/بـــطاطا مـــقليّة - حـــجم كـــبير.png",
    productPrice: "10",
    productKaloris: "377",
  ),
  (
    productTitle: "بـــطاطا مـــقليّة - حـــجم مـــتوسّط",
    productSubTitle: "French Fries (Medium)",
    productImg: "img/new/بـــطاطا مـــقليّة - حـــجم مـــتوسّط.png",
    productPrice: "7",
    productKaloris: "259",
  ),
  (
    productTitle: "بـــطاطا مـــقليّة - حـــجم صـــغير",
    productSubTitle: "French Fries (Smal)",
    productImg: "img/new/بـــطاطا مـــقليّة - حـــجم صـــغير.png",
    productPrice: "5",
    productKaloris: "196",
  ),
];

// ======================== Cold Appetizers Section ===============================================================
List ColdAppetizersSection = [
  (
    productTitle: "تـــبّوله",
    productSubTitle: "Tabbouleh",
    productImg: "img/new/تـــبّوله.png",
    productPrice: "15",
    productKaloris: "70",
  ),
  (
    productTitle: "فـــتّوش",
    productSubTitle: "Fattoush",
    productImg: "img/new/فـــتّوش.png",
    productPrice: "15",
    productKaloris: "132",
  ),
  (
    productTitle: "ســـلطة خـــضراء",
    productSubTitle: "Green Salad",
    productImg: "img/new/ســـلطة خـــضراء.png",
    productPrice: "15",
    productKaloris: "80",
  ),
  (
    productTitle: "ســـلطة ســـيزر",
    productSubTitle: "Cesar Salad",
    productImg: "img/new/ســـلطة ســـيزر.png",
    productPrice: "20",
    productKaloris: "281",
  ),
  (
    productTitle: "ورق عـــنب 10ح ",
    productSubTitle: "Grape Leaves 10p",
    productImg: "img/new/ورق عـــنب 10ح.png",
    productPrice: "18",
    productKaloris: "250",
  ),
  (
    productTitle: "ورق عـــنب 5ح",
    productSubTitle: "Grape Leaves 5p",
    productImg: "img/new/ورق عـــنب 5ح.png",
    productPrice: "10",
    productKaloris: "125",
  ),
  (
    productTitle: "حـــمص",
    productSubTitle: "Hummus",
    productImg: "img/new/حـــمص.png",
    productPrice: "12",
    productKaloris: "490",
  ),
  (
    productTitle: "بـــابا غـــنوج",
    productSubTitle: "Baba Ghanoush",
    productImg: "img/new/بـــابا غـــنوج.png",
    productPrice: "12",
    productKaloris: "120",
  ),
  (
    productTitle: "مـــتبّل",
    productSubTitle: "Mutabal",
    productImg: "img/new/مـــتبّل.png",
    productPrice: "12",
    productKaloris: "145",
  ),
  (
    productTitle: "مـــقبّلات مـــشكّلة",
    productSubTitle: " Mixed Appetizers",
    productImg: "img/new/مـــقبّلات مـــشكّلة.png",
    productPrice: "25",
    productKaloris: "212",
  ),
];

// ========================= Hot_Section ==============================================================
List HotSection = [
  (
    productTitle: "أرز",
    productSubTitle: "Zinger",
    productImg: "img/new/أرز.png",
    productPrice: "18",
    productKaloris: "550",
  ),
  (
    productTitle: "شـــوربة عـــدس",
    productSubTitle: " Mixed Appetizers",
    productImg: "img/new/شـــوربة عـــدس.png",
    productPrice: "6",
    productKaloris: "175",
  ),
];

// ======================= Pastries ================================================================
List Pastries = [
  (
    productTitle: "شـــرحات على العـــجين - وجـــبة",
    productSubTitle: " Slice In Dough (Meal)",
    productImg: "img/new/شـــرحات على العـــجين - وجـــبة.png",
    productPrice: "40",
    productKaloris: "210",
  ),
  (
    productTitle: "نـــصف كـــيلو شـــرحات على العـــجين",
    productSubTitle: " Slice In Dough (Kilo)",
    productImg: "img/new/نـــصف كـــيلو شـــرحات على العـــجين.png",
    productPrice: "170",
    productKaloris: "2100",
  ),
  (
    productTitle: "مـــجرمشة ســـادة - وجـــبة",
    productSubTitle: "Plain Majramish (Meal)",
    productImg: "img/new/مـــجرمشة ســـادة - وجـــبة.png",
    productPrice: "40",
    productKaloris: "350",
  ),
  (
    productTitle: "نـــصف كـــيلو مـــجرمشة ســـادة",
    productSubTitle: "Plain Majramish (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو مـــجرمشة ســـادة.png",
    productPrice: "90",
    productKaloris: "1700",
  ),
  (
    productTitle: "كـــيلو مـــجرمشة ســـادة",
    productSubTitle: "Plain Majramish (Kilo)",
    productImg: "img/new/كـــيلو مـــجرمشة ســـادة.png",
    productPrice: "170",
    productKaloris: "3450",
  ),
  (
    productTitle: "مـــجرمشة مع الخـــضار - وجـــبة",
    productSubTitle: "Majramish with Vegetables (Meal)",
    productImg: "img/new/مـــجرمشة مع الخـــضار - وجـــبة.png",
    productPrice: "40",
    productKaloris: "368",
  ),
  (
    productTitle: "نـــصف كـــيلو مـــجرمشة مع الخـــضار",
    productSubTitle: "Majramish with Vegetables (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو مـــجرمشة مع الخـــضار.png",
    productPrice: "90",
    productKaloris: "1840",
  ),
  (
    productTitle: " كـــيلو مـــجرمشة مع الخـــضار",
    productSubTitle: "Majramish with Vegetables (Kilo)",
    productImg: "img/new/كـــيلو مـــجرمشة مع الخـــضار.png",
    productPrice: "170",
    productKaloris: "3640",
  ),
  (
    productTitle: "صـــفيحة دبـــس رمـــان - وجـــبة",
    productSubTitle: "Pomegranate Molasses Sfeeha (Meal)",
    productImg: "img/new/صـــفيحة دبـــس رمـــان - وجـــبة.png",
    productPrice: "35",
    productKaloris: "340",
  ),
  (
    productTitle: "صـــفيحة أرمـــانيّة - وجـــبة",
    productSubTitle: "Pomegranate Molasses Sfeeha (Half Kilo)",
    productImg: "img/new/صـــفيحة أرمـــانيّة - وجـــبة.png",
    productPrice: "75",
    productKaloris: "1650",
  ),
  (
    productTitle: " كـــيلو صـــفيحة دبـــس رمـــان",
    productSubTitle: "Pomegranate Molasses Sfeeha (Half Kilo)",
    productImg: "img/new/كـــيلو صـــفيحة دبـــس رمـــان.png",
    productPrice: "140",
    productKaloris: "3400",
  ),
  (
    productTitle: "صـــفيحة بـــندورة - وجـــبة",
    productSubTitle: " Tomato Sfeeha (Meal)",
    productImg: "img/new/نـــصف كـــيلو صـــفيحة بـــندورة.png",
    productPrice: "35",
    productKaloris: "280",
  ),
  (
    productTitle: "نـــصف كـــيلو صـــفيحة بـــندورة",
    productSubTitle: " Tomato Sfeeha (Half Kil+D97:D98o)",
    productImg: "img/new/نـــصف كـــيلو صـــفيحة بـــندورة.png",
    productPrice: "75",
    productKaloris: "1400",
  ),
  (
    productTitle: "كـــيلو صـــفيحة بـــندورة",
    productSubTitle: "Tomato Sfeeha (Kilo)",
    productImg: "img/new/كـــيلو صـــفيحة بـــندورة.png",
    productPrice: "140",
    productKaloris: "2850",
  ),
  (
    productTitle: "صـــفيحة أرمـــانيّة - وجـــبة",
    productSubTitle: " Armani Sfeeha (Meal)",
    productImg: "img/new/صـــفيحة أرمـــانيّة - وجـــبة.png",
    productPrice: "35",
    productKaloris: "175",
  ),
  (
    productTitle: "نـــصف كـــيلو صـــفيحة أرمـــانيّة",
    productSubTitle: "Armani Sfeeha (Half Kilo)",
    productImg: "img/new/نـــصف كـــيلو صـــفيحة أرمـــانيّة.png",
    productPrice: "75",
    productKaloris: "1320",
  ),
  (
    productTitle: "كـــيلو صـــفيحة أرمـــانيّة",
    productSubTitle: "Armani Sfeeha (Kilo)",
    productImg: "img/new/كـــيلو صـــفيحة أرمـــانيّة.png",
    productPrice: "140",
    productKaloris: "2650",
  ),
  (
    productTitle: "بـــيتزا مـــارغريتا",
    productSubTitle: "Margherita Pizza",
    productImg: "img/new/بـــيتزا مـــارغريتا.png",
    productPrice: "18",
    productKaloris: "2448",
  ),
  (
    productTitle: "بـــيتزا الفـــصول الأربـــعة",
    productSubTitle: "Four Seasons Pizza",
    productImg: "img/new/بـــيتزا الفـــصول الأربـــعة.png",
    productPrice: "18",
    productKaloris: "2747",
  ),
  (
    productTitle: "بـــيتزا خـــضار",
    productSubTitle: "Vegetables Pizza",
    productImg: "img/new/بـــيتزا خـــضار.png",
    productPrice: "18",
    productKaloris: "2160",
  ),
  (
    productTitle: "مـــنقوشة زعـــتر",
    productSubTitle: " Zaatar Manoushe",
    productImg: "img/new/مـــنقوشة زعـــتر.png",
    productPrice: "10",
    productKaloris: "357",
  ),
  (
    productTitle: "مـــنقوشة مـــحمّره قـــشقوان",
    productSubTitle: "Muhammara Kashkaval Manoushe",
    productImg: "img/new/مـــنقوشة مـــحمّره قـــشقوان.png",
    productPrice: "14",
    productKaloris: "422",
  ),
  (
    productTitle: "مـــنقوشة مـــحمّره",
    productSubTitle: "Muhammara Manoushe",
    productImg: "img/new/مـــنقوشة مـــحمّره.png",
    productPrice: "12",
    productKaloris: "371",
  ),
  (
    productTitle: "مـــنقوشة قـــشقوان",
    productSubTitle: "Kashkaval Manoushe",
    productImg: "img/new/مـــنقوشة قـــشقوان.png",
    productPrice: "13",
    productKaloris: "400",
  ),
  (
    productTitle: "مـــنقوشة عـــكاوي وقـــشقوان",
    productSubTitle: "Akkawi & Kashkaval Manoushe",
    productImg: "img/new/مـــنقوشة عـــكاوي وقـــشقوان.png",
    productPrice: "12",
    productKaloris: "494",
  ),
  (
    productTitle: "جـــبنة عـــكاوي",
    productSubTitle: "Akkawi Cheese",
    productImg: "img/new/جـــبنة عـــكاوي.png",
    productPrice: "14",
    productKaloris: "458",
  ),
  (
    productTitle: "مـــنقوشة لـــبنه وعـــسل",
    productSubTitle: "Labaneh & Honey Manoushe",
    productImg: "img/new/مـــنقوشة لـــبنه وعـــسل.png",
    productPrice: "11",
    productKaloris: "360",
  ),
  (
    productTitle: "مـــنقوشة مـــرتديلا مع الجبن",
    productSubTitle: "Mortadella & Cheese Manoushe",
    productImg: "img/new/مـــنقوشة مـــرتديلا مع الجبن.png",
    productPrice: "14",
    productKaloris: "898",
  ),
  (
    productTitle: "مـــنقوشة لـــبنه وزعـــتر",
    productSubTitle: "Labaneh & Zaatar Manoushe",
    productImg: "img/new/مـــنقوشة لـــبنه وزعـــتر.png",
    productPrice: "11",
    productKaloris: "576",
  ),
  (
    productTitle: "مـــنقوشة لـــحم ســـاده",
    productSubTitle: "Plain Meat Manoushe",
    productImg: "img/new/مـــنقوشة لـــحم ســـاده.png",
    productPrice: "16",
    productKaloris: "876",
  ),
  (
    productTitle: "مـــنقوشة لـــحم مع الجـــبنه",
    productSubTitle: "Meat & Cheese Manoushe",
    productImg: "img/new/مـــنقوشة لـــحم مع الجـــبنه.png",
    productPrice: "18",
    productKaloris: "838",
  ),
  (
    productTitle: "مـــنقوشة لـــبنه",
    productSubTitle: "Manoushe Labna",
    productImg: "img/new/مـــنقوشة لـــبنه.png",
    productPrice: "10",
    productKaloris: "518",
  ),
  (
    productTitle: "مـــنقوشة زعـــتر بالخـــضار",
    productSubTitle: "Manoushe Vegetables with Zaatar",
    productImg: "img/new/مـــنقوشة زعـــتر بالخـــضار.png",
    productPrice: "12",
    productKaloris: "400",
  ),
  (
    productTitle: "مـــنقوشة ســـبانخ",
    productSubTitle: "Manoushe Spinach",
    productImg: "img/new/مـــنقوشة ســـبانخ.png",
    productPrice: "10",
    productKaloris: "432",
  ),
  (
    productTitle: "شـــختور جـــبنه",
    productSubTitle: "Shaktoor Cheese",
    productImg: "img/new/شـــختور جـــبنه.png",
    productPrice: "3",
    productKaloris: "580",
  ),
];

// ============================= Western Food ==========================================================
List Western_Food = [
  (
    productTitle: "زنـــجر",
    productSubTitle: "Rice",
    productImg: "img/new/زنـــجر.png",
    productPrice: "8",
    productKaloris: "130",
  ),
  (
    productTitle: "كـــرسبي",
    productSubTitle: "Crispy",
    productImg: "img/new/كـــرسبي.png",
    productPrice: "18",
    productKaloris: "780",
  ),
  (
    productTitle: "بـــرجر لـــحم",
    productSubTitle: "Beef Burger",
    productImg: "img/new/بـــرجر لـــحم.png",
    productPrice: "20",
    productKaloris: "701",
  ),
  (
    productTitle: "بـــرجر دجـــاج",
    productSubTitle: "Chicken Burger",
    productImg: "img/new/بـــرجر دجـــاج.png",
    productPrice: "20",
    productKaloris: "520",
  ),
  (
    productTitle: "بـــرجر شـــاورما",
    productSubTitle: "Burger Shawarma",
    productImg: "img/new/بـــرجر شـــاورما.png",
    productPrice: "18",
    productKaloris: "788",
  ),
  (
    productTitle: "مـــكسيكي",
    productSubTitle: "Mexican",
    productImg: "img/new/مـــكسيكي.png",
    productPrice: "18",
    productKaloris: "974",
  ),
  (
    productTitle: "فـــرانسيسكو",
    productSubTitle: "Francisco",
    productImg: "img/new/فـــرانسيسكو.png",
    productPrice: "18",
    productKaloris: "607",
  ),
  (
    productTitle: "بـــريوش شـــاورما",
    productSubTitle: "Brioche Shawarma",
    productImg: "img/new/بـــريوش شـــاورما.png",
    productPrice: "18",
    productKaloris: "918",
  ),
  (
    productTitle: "بـــيستو",
    productSubTitle: "Pesto",
    productImg: "img/new/بـــيستو.png",
    productPrice: "18",
    productKaloris: "492",
  ),
  (
    productTitle: "فـــتّة شـــاورما",
    productSubTitle: "Fataa Shawarma",
    productImg: "img/new/فـــتّة شـــاورما.png",
    productPrice: "18",
    productKaloris: "870",
  ),
  (
    productTitle: "كـــريسبي رول",
    productSubTitle: "Crispy Roll",
    productImg: "img/new/كـــريسبي رول.png",
    productPrice: "20",
    productKaloris: "1353",
  ),
  (
    productTitle: "كـــاساديا",
    productSubTitle: "Quesadilla",
    productImg: "img/new/كـــاساديا.png",
    productPrice: "22",
    productKaloris: "486",
  ),
];

// ======================= Drinks ================================================================
List Drinks = [
  (
    productTitle: "مـــشروبات غـــازيّة",
    productSubTitle: "Soft Drinks",
    productImg: "img/new/مـــشروبات غـــازيّة.png",
    productPrice: "4",
    productKaloris: "170",
  ),
  (
    productTitle: "مـــاء",
    productSubTitle: "Water",
    productImg: "img/new/مـــاء.png",
    productPrice: "2",
    productKaloris: "0",
  ),
  (
    productTitle: "كـــوكتيل",
    productSubTitle: "Cocktail",
    productImg: "img/new/كـــوكتيل.png",
    productPrice: "16",
    productKaloris: "124",
  ),
  (
    productTitle: "مـــانجه",
    productSubTitle: "Mango",
    productImg: "img/new/مـــانجه.png",
    productPrice: "14",
    productKaloris: "60",
  ),
  (
    productTitle: "جـــوافة",
    productSubTitle: "Guava",
    productImg: "img/new/جـــوافة.png",
    productPrice: "12",
    productKaloris: "68",
  ),
  (
    productTitle: "فـــراولة",
    productSubTitle: "Strawberry",
    productImg: "img/new/فـــراولة.png",
    productPrice: "12",
    productKaloris: "33",
  ),
  (
    productTitle: "رمـــان",
    productSubTitle: "Pomegranate",
    productImg: "img/new/رمـــان.png",
    productPrice: "14",
    productKaloris: "83",
  ),
  (
    productTitle: "بـــرتقال",
    productSubTitle: "Orange",
    productImg: "img/new/بـــرتقال.png",
    productPrice: "14",
    productKaloris: "47",
  ),
  (
    productTitle: "لـــيمون نـــعناع",
    productSubTitle: "Lemon Mint",
    productImg: "img/new/لـــيمون نـــعناع.png",
    productPrice: "12",
    productKaloris: "50",
  ),
  (
    productTitle: "لـــبن عـــيران",
    productSubTitle: "Yogurt Ayran",
    productImg: "img/new/لـــبن عـــيران.png",
    productPrice: "6",
    productKaloris: "30",
  ),
];

// ======================= ================================================================
